post_install() {

#Add 'games' group if not already there
getent group games > /dev/null || /usr/sbin/groupadd -g 50 games

cat << EOF
==>
==> To be able to play, save configs, and update PlaneShift,
==> add your user to the games group:
==> # gpasswd -a USERNAME games
==> 
EOF
 
}

post_upgrade() {

post_install
  
}

post_remove() {

cat << EOF
==>
==> Please note that some of the data files where removed
==> remove them manually by:
==> # rm -r /usr/share/btanks
EOF

}


