#!/bin/bash

GLESTDIR="/opt/glest"

[ -d ~/.glest ] || mkdir ~/.glest
[ -e ~/.glest/glest ] || ln -s $GLESTDIR/glest ~/.glest/glest
[ -e ~/.glest/glest.ini ] || cp $GLESTDIR/glest.ini ~/.glest/glest.ini

for d in data techs maps tilesets scenarios; do
    [ -d ~/.glest/$d ] || ln -s $GLESTDIR/$d ~/.glest/$d
done

cd ~/.glest
exec ./glest "$@"
