#!/bin/bash

#   aurcmp - compare package versions between repo and AUR
#
#   Copyright (c) 2009 by Arkham <arkham at archlinux dot us>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.


badarg () {
    echo "aurcmp: Try \`aurcmp -h' for more information." >&2
}

usage () {
    echo "aurcmp: compare package versions between repo and AUR"
    echo "usage: aurcmp [OPTIONS]"
    echo
    echo "OPTIONS:"
    echo " -b:      compare both pkgver and pkgrel [default]"
    echo " -c:      colorful output [default]"
    echo " -h:      show this help and quit"
    echo " -n:      nocolor, plain and simple output"
    echo " -o:      compare only pkgver ignoring pkgrel"
    echo " -q:      quiet, display only updates"
    echo " -r REPO: compare packages from selected REPO"
    echo " -v:      verbose, display all packages [default]"
    echo
}

aurcmp () {

    # Create temporary url and get PKGBUILD
    pkgname="$1"
    url="http://aur.archlinux.org/packages/$pkgname/$pkgname/PKGBUILD"

    PKGBUILD=$(wget -q -O - "$url" | grep -E '^(pkgver|pkgrel)=') || {
        # Package not found in AUR
        if [[ "$VERBOSE" == "true" ]]; then
            if [[ "$COLOR" == "true" ]]; then
                echo -e "$pkgname: ${RED}not found in AUR${NC}"
            else
                echo "$pkgname: not found in AUR"
            fi
        fi
        return 0
    }

    # Compare versions
    aurver="$(eval "$PKGBUILD" &>/dev/null; echo "$pkgver-$pkgrel")" || true
    repover="$(LANG=C pacman -Si "$pkgname" | awk '/^Version/ {print $3}')"
    if [[ "$ONLYVER" == "true" ]]; then
        aurver="$(echo "$aurver" | cut -d'-' -f1)"
        repover="$(echo "$repover" | cut -d'-' -f1)"
    fi

    result=$(vercmp "$repover" "$aurver") || true

    # Main switch
    if [[ "$result" < 0 ]]; then
        if [[ "$COLOR" == "true" ]]; then
            echo -e "$pkgname: ${GREEN}$repover => $aurver${NC}"
        else
            echo "$pkgname: $repover => $aurver"
        fi
    elif [[ "$VERBOSE" == "true" ]]; then
        if [[ "$result" > 0 ]]; then
            if [[ "$COLOR" == "true" ]]; then
                echo -e "$pkgname: (${RED}repo=$repover ${NC}aur=$aurver)"
            else
                echo "$pkgname: (repo=$repover aur=$aurver)"
            fi
        else
            echo "$pkgname: up to date"
        fi
    fi
}

# Safety options:
# - no unset variables
set -o nounset
# - no errors in return values
set -o errexit

# Flags default values
COLOR="true"
ONLYVER="false"
VERBOSE="true"
# Colors
RED='\e[1;31m'
GREEN='\e[1;32m'
NC='\e[0m'

while getopts ":bchnoqr:v" opt; do
    case "$opt" in
        "b")
            ONLYVER="false"
            ;;
        "c")
            COLOR="true"
            ;;
        "h")
            usage
            exit 0
            ;;
        "n")
            COLOR="false"
            ;;
        "o")
            ONLYVER="true"
            ;;
        "q")
            VERBOSE="false"
            ;;
        "r")
            REPO="$OPTARG"
            ;;
        "v")
            VERBOSE="true"
            ;;
        "?")
            echo "aurcmp: invalid option: -$OPTARG" >&2
            badarg
            exit 1
            ;;
        ":")
            echo "aurcmp: option -$OPTARG requires an argument." >&2
            badarg
            exit 1
            ;;
        *)
            echo "aurcmp: unknown error while processing options." >&2
            badarg
            exit 1
            ;;
    esac
done

# [arch-games] ftw!
REPO=${REPO:-"arch-games"}

# Main loop
for pkg in $(pacman -Slq $REPO); do 
    aurcmp "$pkg"
done

exit 0
