#!/bin/bash
# run this script in your packages dir
for dir in $(ls)
  do
  if [ -e $dir/PKGBUILD ]; then
  source $dir/PKGBUILD
  
  # find deps
  len=${#depends[@]}
  for ((i=0; i<$len; i++));
    do
    if [ $1 == ${depends[i]} ]; then
      echo dep: $pkgname
    fi
    done
  # find makedeps
  if [ -n ${makedepends} ]; then
    len=${#makedepends[@]}
    for ((i=0; i<$len; i++));
    do
        if [ "$1" == "${makedepends[i]}" ]; then
            echo $pkgname
        fi
    done
  fi
  fi
  done
  #erase for non depending packages
  depends={""}
  #erase makedepends for PKGBUILDs that don't have it
  makedepends={""}



